/*
* Generated file
*
* Generated from: yang module name: odl-switch-impl yang module local name: odl-switch-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Jul 12 18:09:25 IST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package com.talentica.sdn.odlofsoftswitch.impl;
public class OfCapFluxModuleFactory extends com.talentica.sdn.odlofsoftswitch.impl.AbstractOfCapFluxModuleFactory {

}
